import { StyleSheet, Dimensions } from "react-native";
import { colors } from "../../colors";
const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 50,
  },
  header: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 5,
  },
  headerSubtitle: {
    fontSize: 16,
    color: colors.cinza,
  },
  divSearchNotify: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  buttonInputSearchLocation: {
    flexDirection: "row",
    flex: 1,
    height: 50,
    backgroundColor: colors.white,
    borderRadius: 25,
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  inputSearchPlaceholder: {
    flex: 1,
    color: colors.cinza,
    fontSize: 16,
  },
  listContainer: {
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  columnWrapper: {
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  serviceCard: {
    width: (width - 40) / 2,
    backgroundColor: colors.white,
    borderRadius: 15,
    marginBottom: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 3,
  },
  serviceImageContainer: {
    width: "100%",
    height: 140,
    backgroundColor: colors.cinza,
  },
  serviceImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    backgroundColor: colors.cinza,
    justifyContent: "center",
    alignItems: "center",
  },
  serviceInfo: {
    padding: 12,
  },
  serviceName: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 8,
    minHeight: 40,
  },
  servicePrice: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.azulPrincipal,
    marginBottom: 10,
  },
  serviceMeta: {
    marginBottom: 12,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  metaText: {
    fontSize: 11,
    color: colors.cinza,
    marginLeft: 6,
  },
  buttonSchedule: {
    backgroundColor: colors.azulPrincipal,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 10,
  },
  buttonScheduleText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  loadingText: {
    marginTop: 10,
    color: colors.text,
    fontSize: 16,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
    marginTop: 20,
    marginBottom: 10,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.cinza,
    textAlign: "center",
  },
  
  // Modal styles
  viewModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  viewContentModal: {
    backgroundColor: colors.background,
    padding: 20,
    width: "90%",
    maxHeight: "80%",
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  headerModal: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  titleModal: {
    fontWeight: "bold",
    fontSize: 20,
    color: colors.text,
  },
  modalLabelForm: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    width: "100%",
  },
  modalIconForm: {
    marginRight: 10,
  },
  inputModal: {
    borderBottomWidth: 2,
    borderBottomColor: colors.cinza,
    padding: 5,
    width: width * 0.7,
    color: colors.text,
    fontSize: 16,
  },
  searchResults: {
    width: "100%",
    marginBottom: 20,
  },
  resultsTitle: {
    fontSize: 16,
    color: colors.text,
    marginBottom: 10,
    fontWeight: "600",
  },
  searchResultItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  resultImage: {
    width: 60,
    height: 60,
    borderRadius: 10,
    marginRight: 12,
  },
  resultInfo: {
    flex: 1,
  },
  resultName: {
    fontWeight: "bold",
    color: colors.text,
    fontSize: 16,
    marginBottom: 4,
  },
  resultPrice: {
    color: colors.azulPrincipal,
    fontWeight: "bold",
    fontSize: 18,
  },
  buttonSearchPlace: {
    backgroundColor: colors.azulPrincipal,
    height: 50,
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    marginTop: 10,
  },
  buttonTextSearchPlace: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  
  // Estilos do modal de agendamento
  selectedServiceContainer: {
    backgroundColor: "#F0F8FF",
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: colors.azulPrincipal,
  },
  selectedServiceLabel: {
    fontSize: 12,
    color: colors.cinza,
    marginBottom: 5,
  },
  selectedServiceName: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.text,
    marginBottom: 5,
  },
  selectedServicePrice: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.azulPrincipal,
  },
  formContainer: {
    width: "100%",
  },
  formLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 8,
    marginTop: 15,
  },
  formInput: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    color: colors.text,
    backgroundColor: "#FAFAFA",
  },
  textArea: {
    minHeight: 100,
    paddingTop: 12,
  },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 10,
    padding: 12,
    backgroundColor: "#FAFAFA",
  },
  dateButtonText: {
    fontSize: 16,
    color: colors.text,
    marginLeft: 10,
    flex: 1,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 25,
    marginBottom: 10,
  },
  modalButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 15,
    borderRadius: 10,
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: "#F5F5F5",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  cancelButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
  },
  confirmButton: {
    backgroundColor: colors.azulPrincipal,
  },
  confirmButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
});

