import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  scrollViewStyle: {
    flex: 1,
    width: "100%",
  },
  scrollViewContainer: {
    padding: 20,
    paddingBottom: 40,
    alignItems: "center",
  },
  welcomeText: {
    color: "#1E232C",
    fontWeight: "bold",
    fontSize: 27,
    marginBottom: 20,
  },
  sectionText: {
    fontSize: 20,
    color: "#000000",
    fontWeight: "bold",
    marginTop: 10,
    marginBottom: 10,
  },
  sectionTextSub: {
    fontSize: 15,
    color: "#000000",
    fontWeight: "bold",
    marginTop: 10,
    marginLeft: 10,
  },
  descriptionText: {
    fontSize: 15,
    color: "#000000",
    marginTop: 10,
    textAlign: "center",
    marginBottom: 20,
  },
  input: {
    backgroundColor: "#E8ECF4",
    marginTop: 10,
    width: 300,
    height: 40,
    borderRadius: 10,
    paddingLeft: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: "#E8ECF4",
    borderRadius: 10,
    width: '90%',
    marginTop: 10,
    marginBottom: 5,
  },
  inputError: {
    borderWidth: 1,
    borderColor: "red",
  },
  errorText: {
    color: "red",
    fontSize: 12,
    marginBottom: 10,
  },
  threeButtons: {
    height: height * 0.08,
    width: "70%",
    backgroundColor: "#ff6600",
    justifyContent: "center",
    borderRadius: width * 0.02,
    marginBottom: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  clearButton: {
    height: height * 0.08,
    width: "25%",
    backgroundColor: "#666666",
    justifyContent: "center",
    borderRadius: width * 0.02,
    marginBottom: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  registerButton: {
    marginTop: 10,
    backgroundColor: "#ff6600",
    justifyContent: "center",
    width: "80%",
    height: 60,
    borderRadius: 10,
    alignItems: "center",
  },
  buttonText: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 14,
    paddingHorizontal: 5,
  },
  pickerContainer: {
    backgroundColor: "#E8ECF4",
    marginTop: 10,
    width: 300,
    height: 50,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  pickerText: {
    fontSize: 16,
    color: "#000000",
  },
  pickerArrow: {
    fontSize: 16,
    color: "#000000",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    width: "90%",
    paddingVertical: 10,
  },
  modalOption: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E8ECF4",
  },
  modalOptionText: {
    fontSize: 16,
    color: "#000000",
  },
  iconContainer: {
    marginTop: 10,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "90%",
  },
  passwordIcon: {
    padding: 10,
  },
});