import { StyleSheet } from "react-native";
import { colors } from "../../colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  servicesButton: {
    backgroundColor: colors.azulPrincipal,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  servicesButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 6,
  },
  addButton: {
    backgroundColor: colors.azulPrincipal,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 20,
  },
  content: {
    flex: 1,
  },
  item: {
    backgroundColor: colors.white,
    padding: 16,
    marginVertical: 8,
    borderRadius: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  itemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: "600",
    color: colors.primary,
    flex: 1,
    marginRight: 10,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: "bold",
  },
  description: {
    fontSize: 14,
    color: colors.cinza,
    marginBottom: 8,
  },
  infoContainer: {
    marginBottom: 8,
  },
  clientText: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 2,
  },
  driverText: {
    fontSize: 14,
    color: colors.text,
    marginBottom: 2,
  },
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  dateText: {
    fontSize: 13,
    color: colors.primary,
    marginLeft: 6,
  },
  valueContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  valueText: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.azulPrincipal,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
  },
  emptyMessage: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    color: colors.text,
    marginTop: 20,
    marginBottom: 10,
  },
  emptySubtext: {
    textAlign: "center",
    fontSize: 14,
    color: colors.cinza,
  },
  serviceContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    backgroundColor: "#F5F5F5",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  serviceText: {
    fontSize: 13,
    color: colors.primary,
    marginLeft: 6,
    fontWeight: "500",
  },
  phoneText: {
    fontSize: 13,
    color: colors.cinza,
    marginTop: 2,
  },
});